/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // Database and record colors - light mode
    "bg-blue-100",
    "bg-blue-200",
    "bg-blue-500",
    "bg-blue-600",
    "bg-purple-100",
    "bg-purple-200",
    "bg-purple-500",
    "bg-purple-600",
    "bg-green-100",
    "bg-green-200",
    "bg-green-500",
    "bg-green-600",
    "bg-red-100",
    "bg-red-200",
    "bg-red-500",
    "bg-red-600",
    "bg-cyan-100",
    "bg-cyan-200",
    "bg-cyan-500",
    "bg-cyan-600",
    "bg-amber-100",
    "bg-amber-200",
    "bg-amber-500",
    "bg-amber-600",
    "bg-pink-100",
    "bg-pink-200",
    "bg-pink-500",
    "bg-pink-600",
    "bg-orange-100",
    "bg-orange-200",
    "bg-orange-500",
    "bg-orange-600",
    "bg-indigo-100",
    "bg-indigo-200",
    "bg-indigo-500",
    "bg-indigo-600",
    "bg-teal-100",
    "bg-teal-200",
    "bg-teal-500",
    "bg-teal-600",

    // Database and record colors - dark mode
    "dark:bg-blue-800",
    "dark:bg-blue-900",
    "dark:bg-blue-500",
    "dark:bg-blue-600",
    "dark:bg-purple-800",
    "dark:bg-purple-900",
    "dark:bg-purple-500",
    "dark:bg-purple-600",
    "dark:bg-green-800",
    "dark:bg-green-900",
    "dark:bg-green-500",
    "dark:bg-green-600",
    "dark:bg-red-800",
    "dark:bg-red-900",
    "dark:bg-red-500",
    "dark:bg-red-600",
    "dark:bg-cyan-800",
    "dark:bg-cyan-900",
    "dark:bg-cyan-500",
    "dark:bg-cyan-600",
    "dark:bg-amber-800",
    "dark:bg-amber-900",
    "dark:bg-amber-500",
    "dark:bg-amber-600",
    "dark:bg-pink-800",
    "dark:bg-pink-900",
    "dark:bg-pink-500",
    "dark:bg-pink-600",
    "dark:bg-orange-800",
    "dark:bg-orange-900",
    "dark:bg-orange-500",
    "dark:bg-orange-600",
    "dark:bg-indigo-800",
    "dark:bg-indigo-900",
    "dark:bg-indigo-500",
    "dark:bg-indigo-600",
    "dark:bg-teal-800",
    "dark:bg-teal-900",
    "dark:bg-teal-500",
    "dark:bg-teal-600",

    // Border colors
    "border-blue-500",
    "border-purple-500",
    "border-green-500",
    "border-red-500",
    "border-cyan-500",
    "border-amber-500",
    "border-pink-500",
    "border-orange-500",
    "border-indigo-500",
    "border-teal-500",
    "dark:border-blue-600",
    "dark:border-purple-600",
    "dark:border-green-600",
    "dark:border-red-600",
    "dark:border-cyan-600",
    "dark:border-amber-600",
    "dark:border-pink-600",
    "dark:border-orange-600",
    "dark:border-indigo-600",
    "dark:border-teal-600",

    // Text colors
    "text-blue-100",
    "text-blue-900",
    "text-purple-100",
    "text-purple-900",
    "text-green-100",
    "text-green-900",
    "text-red-100",
    "text-red-900",
    "text-cyan-100",
    "text-cyan-900",
    "text-amber-100",
    "text-amber-900",
    "text-pink-100",
    "text-pink-900",
    "text-orange-100",
    "text-orange-900",
    "text-indigo-100",
    "text-indigo-900",
    "text-teal-100",
    "text-teal-900",
    "dark:text-blue-100",
    "dark:text-purple-100",
    "dark:text-green-100",
    "dark:text-red-100",
    "dark:text-cyan-100",
    "dark:text-amber-100",
    "dark:text-pink-100",
    "dark:text-orange-100",
    "dark:text-indigo-100",
    "dark:text-teal-100",

    // Hover states
    "hover:bg-blue-200",
    "hover:bg-purple-200",
    "hover:bg-green-200",
    "hover:bg-red-200",
    "hover:bg-cyan-200",
    "hover:bg-amber-200",
    "hover:bg-pink-200",
    "hover:bg-orange-200",
    "hover:bg-indigo-200",
    "hover:bg-teal-200",
    "dark:hover:bg-blue-800",
    "dark:hover:bg-purple-800",
    "dark:hover:bg-green-800",
    "dark:hover:bg-red-800",
    "dark:hover:bg-cyan-800",
    "dark:hover:bg-amber-800",
    "dark:hover:bg-pink-800",
    "dark:hover:bg-orange-800",
    "dark:hover:bg-indigo-800",
    "dark:hover:bg-teal-800",

    // Other utility classes
    "fill-yellow-400",
    "bg-opacity-50",
    "dark:bg-opacity-50",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

