import type { Database } from "@/types/secure-database"

export const defaultTemplates: Database[] = [
  {
    title: "Project Management",
    color: "emerald",
    fields: [
      { name: "Project Name", type: "text", showOnCard: true },
      { name: "Description", type: "textarea" },
      {
        name: "Status",
        type: "dropdown",
        options: ["Not Started", "Planning", "In Progress", "On Hold", "Completed", "Cancelled"],
        showOnCard: true,
      },
      {
        name: "Priority",
        type: "dropdown",
        options: ["Low", "Medium", "High", "Critical"],
        showOnCard: true,
      },
      { name: "Start Date", type: "date" },
      { name: "Due Date", type: "date", showOnCard: true },
      { name: "Completion Date", type: "date" },
      { name: "Budget", type: "number" },
      { name: "Actual Cost", type: "number" },
      {
        name: "Team Members",
        type: "checkbox",
        options: ["Project Manager", "Developer", "Designer", "QA", "Stakeholder", "Client", "Other"],
      },
      { name: "Client/Stakeholder", type: "text" },
      { name: "Client Contact", type: "text" },
      {
        name: "Tags",
        type: "checkbox",
        options: ["Internal", "External", "Billable", "Non-billable", "Strategic", "Maintenance"],
      },
      { name: "Milestones", type: "textarea" },
      { name: "Risks & Issues", type: "textarea" },
      { name: "Dependencies", type: "textarea" },
      { name: "Notes", type: "textarea" },
      { name: "Documents", type: "gallery" },
    ],
    records: [
      {
        id: "pm-1",
        values: {
          "Project Name": "Alpha Matrix Deployment",
          "Description": "Initializing the global secure architecture for SecureLifeHub nodes.",
          "Status": "In Progress",
          "Priority": "Critical",
          "Start Date": "2026-03-01",
          "Due Date": "2026-04-15",
          "Budget": 50000,
          "Team Members": ["Project Manager", "Developer"],
          "Tags": ["Strategic"]
        },
        isFavorite: true,
        created: "2026-03-01T10:00:00Z",
        lastUpdated: "2026-03-17T14:30:00Z"
      }
    ],
  },
  {
    title: "Customer Relationship Management (CRM)",
    color: "green",
    fields: [
      { name: "Contact Name", type: "text", showOnCard: true },
      { name: "Company", type: "text", showOnCard: true },
      { name: "Job Title", type: "text" },
      { name: "Email", type: "text", showOnCard: true },
      { name: "Phone", type: "text", showOnCard: true },
      { name: "Address", type: "textarea" },
      {
        name: "Status",
        type: "dropdown",
        options: ["New", "Contacted", "Qualified", "Proposal", "Won", "Lost"],
        showOnCard: true
      },
      { name: "Interaction History", type: "textarea" },
      { name: "Files & Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Inventory Management",
    color: "teal",
    fields: [
      { name: "Item Name", type: "text", showOnCard: true },
      { name: "SKU/Product Code", type: "text", showOnCard: true },
      { name: "Category", type: "dropdown", options: ["Equipment", "Supplies", "Retail"], showOnCard: true },
      { name: "Quantity", type: "number", showOnCard: true },
      { name: "Unit Cost", type: "number" },
      { name: "Status", type: "dropdown", options: ["In Stock", "Out of Stock", "On Order"], showOnCard: true },
      { name: "Notes", type: "textarea" },
    ],
    records: [],
  },
  {
    title: "Event Planning",
    color: "cyan",
    fields: [
      { name: "Event Name", type: "text", showOnCard: true },
      { name: "Type", type: "dropdown", options: ["Meeting", "Conference", "Social", "Other"], showOnCard: true },
      { name: "Date", type: "date", showOnCard: true },
      { name: "Location", type: "text", showOnCard: true },
      { name: "Budget", type: "number" },
      { name: "Status", type: "dropdown", options: ["Planning", "Confirmed", "Completed"], showOnCard: true },
    ],
    records: [],
  },
  {
    title: "Recipe Collection",
    color: "indigo",
    fields: [
      { name: "Recipe Title", type: "text", showOnCard: true },
      { name: "Category", type: "dropdown", options: ["Main", "Side", "Dessert", "Drink"], showOnCard: true },
      { name: "Prep Time", type: "number", showOnCard: true },
      { name: "Ingredients", type: "textarea" },
      { name: "Instructions", type: "textarea" },
    ],
    records: [],
  },
  {
    title: "Fitness Log",
    color: "green",
    fields: [
      { name: "Date", type: "date", showOnCard: true },
      { name: "Activity", type: "text", showOnCard: true },
      { name: "Duration", type: "number", showOnCard: true },
      { name: "Intensity", type: "dropdown", options: ["Low", "Medium", "High"], showOnCard: true },
      { name: "Notes", type: "textarea" },
    ],
    records: [],
  },
  {
    title: "Daily Journal & Mood Tracker",
    color: "rose",
    fields: [
      { name: "Entry Date", type: "date", showOnCard: true },
      { name: "Mood", type: "dropdown", options: ["Radiant", "Neutral", "Tired", "Stressed"], showOnCard: true },
      { name: "Morning Notes", type: "textarea" },
      { name: "Evening Recap", type: "textarea" },
      { name: "Gratitude Points", type: "textarea" },
    ],
    records: [],
  },
  {
    title: "Health & Medication Tracker",
    color: "red",
    fields: [
      { name: "Medicine/Vivid", type: "text", showOnCard: true },
      { name: "Dosage", type: "text", showOnCard: true },
      { name: "Frequency", type: "dropdown", options: ["Daily", "Weekly", "As Needed"], showOnCard: true },
      { name: "Remaining Supply", type: "number", showOnCard: true },
      { name: "Medical Provider", type: "text" },
      { name: "Last Taken", type: "date" },
    ],
    records: [],
  },
  {
    title: "Personal Finance & Budgeting",
    color: "amber",
    fields: [
      { name: "Description", type: "text", showOnCard: true },
      { name: "Amount", type: "number", showOnCard: true },
      { name: "Type", type: "dropdown", options: ["Income", "Expense", "Saving"], showOnCard: true },
      { name: "Category", type: "dropdown", options: ["Housing", "Food", "Tech", "Transport"], showOnCard: true },
      { name: "Transaction Date", type: "date", showOnCard: true },
    ],
    records: [],
  },
  {
    title: "Travel Planner & Bucket List",
    color: "blue",
    fields: [
      { name: "Destination", type: "text", showOnCard: true },
      { name: "Estimated Cost", type: "number" },
      { name: "Primary Purpose", type: "dropdown", options: ["Work", "Leisure", "Family"], showOnCard: true },
      { name: "Target Date", type: "date", showOnCard: true },
      { name: "Status", type: "dropdown", options: ["Bucket List", "Planned", "Visited"], showOnCard: true },
      { name: "Must-See Spots", type: "textarea" },
    ],
    records: [],
  },
  {
    title: "Home Inventory & Maintenance",
    color: "pink",
    fields: [
      { name: "Asset Name", type: "text", showOnCard: true },
      { name: "Room/Location", type: "text", showOnCard: true },
      { name: "Purchase Date", type: "date" },
      { name: "Warranty Expiry", type: "date", showOnCard: true },
      { name: "Last Maintenance", type: "date", showOnCard: true },
      { name: "Manual Link", type: "text" },
    ],
    records: [],
  },
  {
    title: "Movie & TV Show Watchlist",
    color: "cyan",
    fields: [
      { name: "Title", type: "text", showOnCard: true },
      { name: "Type", type: "dropdown", options: ["Movie", "Series", "Documentary"], showOnCard: true },
      { name: "Status", type: "dropdown", options: ["To Watch", "In Progress", "Finished"], showOnCard: true },
      { name: "Rating", type: "dropdown", options: ["⭐", "⭐⭐", "⭐⭐⭐", "⭐⭐⭐⭐", "⭐⭐⭐⭐⭐"], showOnCard: true },
      { name: "Streaming Service", type: "text" },
    ],
    records: [],
  },
  {
    title: "Gift Ideas & Shopping List",
    color: "blue",
    fields: [
      { name: "Item/Gift", type: "text", showOnCard: true },
      { name: "Recipient", type: "text", showOnCard: true },
      { name: "Occasion", type: "dropdown", options: ["Birthday", "Holiday", "Anniversary"], showOnCard: true },
      { name: "Price Est", type: "number", showOnCard: true },
      { name: "Status", type: "dropdown", options: ["Idea", "Ordered", "Received", "Wrapped"], showOnCard: true },
    ],
    records: [],
  },
  {
    title: "Meal Planning & Grocery List",
    color: "teal",
    fields: [
      { name: "Meal Day", type: "dropdown", options: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], showOnCard: true },
      { name: "Meal Name", type: "text", showOnCard: true },
      { name: "Status", type: "dropdown", options: ["Planned", "Prepped", "Done"], showOnCard: true },
      { name: "Grocery Items", type: "textarea" },
    ],
    records: [],
  },
  {
    title: "Hobby & Collection Database",
    color: "teal",
    fields: [
      { name: "Collection Item", type: "text", showOnCard: true },
      { name: "Category", type: "text", showOnCard: true },
      { name: "Condition", type: "dropdown", options: ["Mint", "Good", "Used"], showOnCard: true },
      { name: "Acquisition Date", type: "date" },
      { name: "Valuation", type: "number", showOnCard: true },
    ],
    records: [],
  },
  {
    title: "App Development Journal",
    color: "indigo",
    fields: [
      { name: "App Name", type: "text", showOnCard: true },
      { name: "Platforms", type: "checkbox", options: ["Loveable", "Bolt.diy", "Bolt.new", "CodePen", "Cursor", "Windsurf", "GitHub Codespaces", "v0.dev", "Trae", "Antigravity", "N8N", "Tempo"], showOnCard: true },
      { name: "User Names", type: "text", showOnCard: true },
      { name: "Latest Update", type: "text", showOnCard: true },
      { name: "Preview URL", type: "text", showOnCard: true },
      { name: "Published URL", type: "text", showOnCard: true },
      { name: "Initial Request Date", type: "date" },
      { name: "Current Request Date", type: "date" },
      { name: "AI Agents", type: "checkbox", options: ["xAI Grok", "ChatGPT", "Claude", "Google Gemini (Bard)"] },
      { name: "Mission Notes", type: "textarea" },
      { name: "UI Assets", type: "gallery" },
    ],
    records: [
      {
        id: "adj-1",
        values: {
          "App Name": "SecureLifeHub",
          "Platforms": ["Cursor", "Antigravity"],
          "User Names": "RickB54",
          "Latest Update": "Implemented Reporting Engine",
          "Preview URL": "https://preview.securelife.hub",
          "Published URL": "https://securelife.hub",
          "Initial Request Date": "2026-03-01",
          "Current Request Date": "2026-03-18",
          "AI Agents": ["Claude"],
          "Mission Notes": "Focusing on high-fidelity dashboard and secure database module."
        },
        isFavorite: true,
        created: "2026-03-01T10:00:00Z",
        lastUpdated: "2026-03-18T16:00:00Z"
      }
    ],
  },
]
