import type { Database } from "@/types/secure-database"

export const defaultTemplates: Database[] = [
  {
    title: "Project Management",
    fields: [
      { name: "Project Name", type: "text" },
      { name: "Description", type: "textarea" },
      {
        name: "Status",
        type: "dropdown",
        options: ["Not Started", "Planning", "In Progress", "On Hold", "Completed", "Cancelled"],
      },
      {
        name: "Priority",
        type: "dropdown",
        options: ["Low", "Medium", "High", "Critical"],
      },
      { name: "Start Date", type: "date" },
      { name: "Due Date", type: "date" },
      { name: "Completion Date", type: "date" },
      { name: "Budget", type: "number" },
      { name: "Actual Cost", type: "number" },
      {
        name: "Team Members",
        type: "checkbox",
        options: ["Project Manager", "Developer", "Designer", "QA", "Stakeholder", "Client", "Other"],
      },
      { name: "Client/Stakeholder", type: "text" },
      { name: "Client Contact", type: "text" },
      {
        name: "Tags",
        type: "checkbox",
        options: ["Internal", "External", "Billable", "Non-billable", "Strategic", "Maintenance"],
      },
      { name: "Milestones", type: "textarea" },
      { name: "Risks & Issues", type: "textarea" },
      { name: "Dependencies", type: "textarea" },
      { name: "Notes", type: "textarea" },
      { name: "Documents", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Customer Relationship Management (CRM)",
    fields: [
      { name: "Contact Name", type: "text" },
      { name: "Company", type: "text" },
      { name: "Job Title", type: "text" },
      { name: "Email", type: "text" },
      { name: "Phone", type: "text" },
      { name: "Mobile", type: "text" },
      { name: "Address", type: "textarea" },
      { name: "Website", type: "text" },
      {
        name: "Contact Type",
        type: "dropdown",
        options: ["Lead", "Prospect", "Customer", "Partner", "Vendor", "Other"],
      },
      {
        name: "Lead Source",
        type: "dropdown",
        options: ["Website", "Referral", "Social Media", "Event", "Cold Call", "Advertisement", "Other"],
      },
      {
        name: "Status",
        type: "dropdown",
        options: ["New", "Contacted", "Qualified", "Proposal", "Negotiation", "Won", "Lost", "Inactive"],
      },
      { name: "Last Contact Date", type: "date" },
      { name: "Next Follow-up", type: "date" },
      {
        name: "Tags",
        type: "checkbox",
        options: ["VIP", "Decision Maker", "Influencer", "Technical", "Financial", "Hot Lead"],
      },
      { name: "Deal Size", type: "number" },
      { name: "Expected Close Date", type: "date" },
      {
        name: "Priority",
        type: "dropdown",
        options: ["Low", "Medium", "High"],
      },
      { name: "Notes", type: "textarea" },
      { name: "Interaction History", type: "textarea" },
      { name: "Files & Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Inventory Management",
    fields: [
      { name: "Item Name", type: "text" },
      { name: "SKU/Product Code", type: "text" },
      { name: "Description", type: "textarea" },
      {
        name: "Category",
        type: "dropdown",
        options: ["Raw Materials", "Work in Progress", "Finished Goods", "Office Supplies", "Equipment", "Other"],
      },
      { name: "Supplier/Vendor", type: "text" },
      { name: "Quantity in Stock", type: "number" },
      { name: "Reorder Point", type: "number" },
      { name: "Reorder Quantity", type: "number" },
      { name: "Unit Cost", type: "number" },
      { name: "Selling Price", type: "number" },
      { name: "Location", type: "text" },
      { name: "Warehouse/Bin", type: "text" },
      { name: "Date Added", type: "date" },
      { name: "Last Restocked", type: "date" },
      { name: "Expiration Date", type: "date" },
      {
        name: "Status",
        type: "dropdown",
        options: ["In Stock", "Low Stock", "Out of Stock", "Discontinued", "On Order"],
      },
      {
        name: "Tags",
        type: "checkbox",
        options: ["Fragile", "Perishable", "Hazardous", "Oversized", "High Value", "Seasonal"],
      },
      { name: "Notes", type: "textarea" },
      { name: "Product Images", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Event Planning",
    fields: [
      { name: "Event Name", type: "text" },
      { name: "Description", type: "textarea" },
      {
        name: "Event Type",
        type: "dropdown",
        options: ["Meeting", "Conference", "Workshop", "Party", "Wedding", "Corporate", "Fundraiser", "Other"],
      },
      { name: "Start Date", type: "date" },
      { name: "End Date", type: "date" },
      { name: "Start Time", type: "text" },
      { name: "End Time", type: "text" },
      { name: "Location", type: "text" },
      { name: "Venue Details", type: "textarea" },
      { name: "Expected Attendees", type: "number" },
      { name: "Budget", type: "number" },
      { name: "Actual Cost", type: "number" },
      {
        name: "Status",
        type: "dropdown",
        options: ["Planning", "Confirmed", "In Progress", "Completed", "Cancelled"],
      },
      { name: "Host/Organizer", type: "text" },
      { name: "Contact Person", type: "text" },
      { name: "Contact Details", type: "text" },
      {
        name: "Required Services",
        type: "checkbox",
        options: ["Catering", "Photography", "Entertainment", "Decoration", "Transportation", "Accommodation"],
      },
      { name: "Guest List", type: "textarea" },
      { name: "Agenda/Schedule", type: "textarea" },
      { name: "Notes", type: "textarea" },
      { name: "Event Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Recipe Collection",
    fields: [
      { name: "Recipe Name", type: "text" },
      {
        name: "Category",
        type: "dropdown",
        options: [
          "Breakfast",
          "Lunch",
          "Dinner",
          "Appetizer",
          "Side Dish",
          "Dessert",
          "Snack",
          "Beverage",
          "Soup",
          "Salad",
        ],
      },
      {
        name: "Cuisine",
        type: "dropdown",
        options: [
          "American",
          "Italian",
          "Mexican",
          "Asian",
          "Mediterranean",
          "Indian",
          "French",
          "Middle Eastern",
          "Other",
        ],
      },
      { name: "Prep Time (minutes)", type: "number" },
      { name: "Cook Time (minutes)", type: "number" },
      { name: "Total Time (minutes)", type: "number" },
      { name: "Servings", type: "number" },
      {
        name: "Difficulty",
        type: "dropdown",
        options: ["Easy", "Moderate", "Difficult"],
      },
      { name: "Ingredients", type: "textarea" },
      { name: "Instructions", type: "textarea" },
      { name: "Nutritional Info", type: "textarea" },
      {
        name: "Dietary Restrictions",
        type: "checkbox",
        options: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free", "Nut-Free", "Low-Carb", "Keto", "Paleo"],
      },
      {
        name: "Meal Planning Tags",
        type: "checkbox",
        options: ["Quick & Easy", "Make Ahead", "Freezer Friendly", "One Pot", "Budget Friendly", "Kid Friendly"],
      },
      { name: "Source", type: "text" },
      { name: "URL", type: "text" },
      { name: "Date Added", type: "date" },
      { name: "Last Made", type: "date" },
      {
        name: "Rating",
        type: "dropdown",
        options: ["1 - Never Again", "2 - Disappointing", "3 - Good", "4 - Great", "5 - Excellent"],
      },
      { name: "Notes", type: "textarea" },
      { name: "Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Fitness Log",
    fields: [
      { name: "Workout Date", type: "date" },
      {
        name: "Workout Type",
        type: "dropdown",
        options: [
          "Strength Training",
          "Cardio",
          "HIIT",
          "Yoga",
          "Pilates",
          "Swimming",
          "Cycling",
          "Running",
          "Walking",
          "Sports",
          "Other",
        ],
      },
      { name: "Duration (minutes)", type: "number" },
      { name: "Calories Burned", type: "number" },
      {
        name: "Intensity",
        type: "dropdown",
        options: ["Low", "Moderate", "High", "Very High"],
      },
      { name: "Exercises", type: "textarea" },
      { name: "Sets/Reps/Weight", type: "textarea" },
      { name: "Distance (km/mi)", type: "number" },
      { name: "Average Heart Rate", type: "number" },
      { name: "Max Heart Rate", type: "number" },
      {
        name: "Muscle Groups",
        type: "checkbox",
        options: ["Chest", "Back", "Shoulders", "Arms", "Abs", "Legs", "Glutes", "Full Body"],
      },
      { name: "Pre-Workout Weight (kg/lb)", type: "number" },
      { name: "Post-Workout Weight (kg/lb)", type: "number" },
      {
        name: "Mood Before",
        type: "dropdown",
        options: ["Energetic", "Motivated", "Tired", "Stressed", "Neutral"],
      },
      {
        name: "Mood After",
        type: "dropdown",
        options: ["Energized", "Satisfied", "Exhausted", "Sore", "Accomplished"],
      },
      {
        name: "Energy Level",
        type: "dropdown",
        options: ["1 - Very Low", "2 - Low", "3 - Medium", "4 - High", "5 - Very High"],
      },
      { name: "Workout Location", type: "text" },
      { name: "Workout Partner", type: "text" },
      { name: "Notes", type: "textarea" },
      { name: "Photos", type: "gallery" },
    ],
    records: [],
  },
]
