import type { Database } from "./types"

export const defaultTemplates: Database[] = [
  {
    title: "Project Management",
    fields: [
      { name: "Project Name", type: "text" },
      { name: "Description", type: "textarea" },
      {
        name: "Status",
        type: "dropdown",
        options: ["Not Started", "Planning", "In Progress", "On Hold", "Completed", "Cancelled"],
      },
      {
        name: "Priority",
        type: "dropdown",
        options: ["Low", "Medium", "High", "Critical"],
      },
      { name: "Start Date", type: "date" },
      { name: "Due Date", type: "date" },
      { name: "Completion Date", type: "date" },
      { name: "Budget", type: "number" },
      { name: "Actual Cost", type: "number" },
      {
        name: "Team Members",
        type: "checkbox",
        options: ["Project Manager", "Developer", "Designer", "QA", "Stakeholder", "Client", "Other"],
      },
      { name: "Client/Stakeholder", type: "text" },
      { name: "Client Contact", type: "text" },
      {
        name: "Tags",
        type: "checkbox",
        options: ["Internal", "External", "Billable", "Non-billable", "Strategic", "Maintenance"],
      },
      { name: "Milestones", type: "textarea" },
      { name: "Risks & Issues", type: "textarea" },
      { name: "Dependencies", type: "textarea" },
      { name: "Notes", type: "textarea" },
      { name: "Documents", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Customer Relationship Management (CRM)",
    fields: [
      { name: "Contact Name", type: "text" },
      { name: "Company", type: "text" },
      { name: "Job Title", type: "text" },
      { name: "Email", type: "text" },
      { name: "Phone", type: "text" },
      { name: "Mobile", type: "text" },
      { name: "Address", type: "textarea" },
      { name: "Website", type: "text" },
      {
        name: "Contact Type",
        type: "dropdown",
        options: ["Lead", "Prospect", "Customer", "Partner", "Vendor", "Other"],
      },
      {
        name: "Lead Source",
        type: "dropdown",
        options: ["Website", "Referral", "Social Media", "Event", "Cold Call", "Advertisement", "Other"],
      },
      {
        name: "Status",
        type: "dropdown",
        options: ["New", "Contacted", "Qualified", "Proposal", "Negotiation", "Won", "Lost", "Inactive"],
      },
      { name: "Last Contact Date", type: "date" },
      { name: "Next Follow-up", type: "date" },
      {
        name: "Tags",
        type: "checkbox",
        options: ["VIP", "Decision Maker", "Influencer", "Technical", "Financial", "Hot Lead"],
      },
      { name: "Deal Size", type: "number" },
      { name: "Expected Close Date", type: "date" },
      {
        name: "Priority",
        type: "dropdown",
        options: ["Low", "Medium", "High"],
      },
      { name: "Notes", type: "textarea" },
      { name: "Interaction History", type: "textarea" },
      { name: "Files & Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Inventory Management",
    fields: [
      { name: "Item Name", type: "text" },
      { name: "SKU/Product Code", type: "text" },
      { name: "Description", type: "textarea" },
      {
        name: "Category",
        type: "dropdown",
        options: ["Raw Materials", "Work in Progress", "Finished Goods", "Office Supplies", "Equipment", "Other"],
      },
      { name: "Supplier/Vendor", type: "text" },
      { name: "Quantity in Stock", type: "number" },
      { name: "Reorder Point", type: "number" },
      { name: "Reorder Quantity", type: "number" },
      { name: "Unit Cost", type: "number" },
      { name: "Selling Price", type: "number" },
      { name: "Location", type: "text" },
      { name: "Warehouse/Bin", type: "text" },
      { name: "Date Added", type: "date" },
      { name: "Last Restocked", type: "date" },
      { name: "Expiration Date", type: "date" },
      {
        name: "Status",
        type: "dropdown",
        options: ["In Stock", "Low Stock", "Out of Stock", "Discontinued", "On Order"],
      },
      {
        name: "Tags",
        type: "checkbox",
        options: ["Fragile", "Perishable", "Hazardous", "Oversized", "High Value", "Seasonal"],
      },
      { name: "Notes", type: "textarea" },
      { name: "Product Images", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Event Planning",
    fields: [
      { name: "Event Name", type: "text" },
      { name: "Description", type: "textarea" },
      {
        name: "Event Type",
        type: "dropdown",
        options: ["Meeting", "Conference", "Workshop", "Party", "Wedding", "Corporate", "Fundraiser", "Other"],
      },
      { name: "Start Date", type: "date" },
      { name: "End Date", type: "date" },
      { name: "Start Time", type: "text" },
      { name: "End Time", type: "text" },
      { name: "Location", type: "text" },
      { name: "Venue Details", type: "textarea" },
      { name: "Expected Attendees", type: "number" },
      { name: "Budget", type: "number" },
      { name: "Actual Cost", type: "number" },
      {
        name: "Status",
        type: "dropdown",
        options: ["Planning", "Confirmed", "In Progress", "Completed", "Cancelled"],
      },
      { name: "Host/Organizer", type: "text" },
      { name: "Contact Person", type: "text" },
      { name: "Contact Details", type: "text" },
      {
        name: "Required Services",
        type: "checkbox",
        options: ["Catering", "Photography", "Entertainment", "Decoration", "Transportation", "Accommodation"],
      },
      { name: "Guest List", type: "textarea" },
      { name: "Agenda/Schedule", type: "textarea" },
      { name: "Notes", type: "textarea" },
      { name: "Event Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Recipe Collection",
    fields: [
      { name: "Recipe Name", type: "text" },
      {
        name: "Category",
        type: "dropdown",
        options: [
          "Breakfast",
          "Lunch",
          "Dinner",
          "Appetizer",
          "Side Dish",
          "Dessert",
          "Snack",
          "Beverage",
          "Soup",
          "Salad",
        ],
      },
      {
        name: "Cuisine",
        type: "dropdown",
        options: [
          "American",
          "Italian",
          "Mexican",
          "Asian",
          "Mediterranean",
          "Indian",
          "French",
          "Middle Eastern",
          "Other",
        ],
      },
      { name: "Prep Time (minutes)", type: "number" },
      { name: "Cook Time (minutes)", type: "number" },
      { name: "Total Time (minutes)", type: "number" },
      { name: "Servings", type: "number" },
      {
        name: "Difficulty",
        type: "dropdown",
        options: ["Easy", "Moderate", "Difficult"],
      },
      { name: "Ingredients", type: "textarea" },
      { name: "Instructions", type: "textarea" },
      { name: "Nutritional Info", type: "textarea" },
      {
        name: "Dietary Restrictions",
        type: "checkbox",
        options: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free", "Nut-Free", "Low-Carb", "Keto", "Paleo"],
      },
      {
        name: "Meal Planning Tags",
        type: "checkbox",
        options: ["Quick & Easy", "Make Ahead", "Freezer Friendly", "One Pot", "Budget Friendly", "Kid Friendly"],
      },
      { name: "Source", type: "text" },
      { name: "URL", type: "text" },
      { name: "Date Added", type: "date" },
      { name: "Last Made", type: "date" },
      {
        name: "Rating",
        type: "dropdown",
        options: ["1 - Never Again", "2 - Disappointing", "3 - Good", "4 - Great", "5 - Excellent"],
      },
      { name: "Notes", type: "textarea" },
      { name: "Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Fitness Log",
    fields: [
      { name: "Workout Date", type: "date" },
      {
        name: "Workout Type",
        type: "dropdown",
        options: [
          "Strength Training",
          "Cardio",
          "HIIT",
          "Yoga",
          "Pilates",
          "Swimming",
          "Cycling",
          "Running",
          "Walking",
          "Sports",
          "Other",
        ],
      },
      { name: "Duration (minutes)", type: "number" },
      { name: "Calories Burned", type: "number" },
      {
        name: "Intensity",
        type: "dropdown",
        options: ["Low", "Moderate", "High", "Very High"],
      },
      { name: "Exercises", type: "textarea" },
      { name: "Sets/Reps/Weight", type: "textarea" },
      { name: "Distance (km/mi)", type: "number" },
      { name: "Average Heart Rate", type: "number" },
      { name: "Max Heart Rate", type: "number" },
      {
        name: "Muscle Groups",
        type: "checkbox",
        options: ["Chest", "Back", "Shoulders", "Arms", "Abs", "Legs", "Glutes", "Full Body"],
      },
      { name: "Pre-Workout Weight (kg/lb)", type: "number" },
      { name: "Post-Workout Weight (kg/lb)", type: "number" },
      {
        name: "Mood Before",
        type: "dropdown",
        options: ["Energetic", "Motivated", "Tired", "Stressed", "Neutral"],
      },
      {
        name: "Mood After",
        type: "dropdown",
        options: ["Energized", "Satisfied", "Exhausted", "Sore", "Accomplished"],
      },
      {
        name: "Energy Level",
        type: "dropdown",
        options: ["1 - Very Low", "2 - Low", "3 - Medium", "4 - High", "5 - Very High"],
      },
      { name: "Workout Location", type: "text" },
      { name: "Workout Partner", type: "text" },
      { name: "Notes", type: "textarea" },
      { name: "Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Daily Journal & Mood Tracker",
    fields: [
      { name: "Date", type: "date" },
      {
        name: "Overall Mood",
        type: "dropdown",
        options: ["Excellent", "Good", "Neutral", "Low", "Very Low"],
      },
      {
        name: "Emotions",
        type: "checkbox",
        options: [
          "Happy",
          "Excited",
          "Calm",
          "Content",
          "Anxious",
          "Stressed",
          "Sad",
          "Angry",
          "Frustrated",
          "Grateful",
        ],
      },
      { name: "Morning Entry", type: "textarea" },
      { name: "Afternoon Entry", type: "textarea" },
      { name: "Evening Entry", type: "textarea" },
      {
        name: "Energy Level",
        type: "dropdown",
        options: ["1 - Exhausted", "2 - Tired", "3 - Average", "4 - Energetic", "5 - Very Energetic"],
      },
      {
        name: "Stress Level",
        type: "dropdown",
        options: ["1 - None", "2 - Mild", "3 - Moderate", "4 - High", "5 - Extreme"],
      },
      { name: "Sleep Hours", type: "number" },
      {
        name: "Sleep Quality",
        type: "dropdown",
        options: ["1 - Poor", "2 - Fair", "3 - Good", "4 - Very Good", "5 - Excellent"],
      },
      {
        name: "Activities",
        type: "checkbox",
        options: ["Work", "Exercise", "Social", "Family", "Learning", "Creative", "Self-care", "Chores", "Relaxation"],
      },
      { name: "Highlights", type: "textarea" },
      { name: "Challenges", type: "textarea" },
      { name: "Gratitude", type: "textarea" },
      { name: "Goals/Intentions", type: "textarea" },
      { name: "Reflections", type: "textarea" },
      { name: "Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Health & Medication Tracker",
    fields: [
      { name: "Date", type: "date" },
      {
        name: "Record Type",
        type: "dropdown",
        options: ["Medication", "Symptom", "Vital Signs", "Doctor Visit", "Test Result", "Other"],
      },
      { name: "Medication/Treatment", type: "text" },
      { name: "Dosage", type: "text" },
      {
        name: "Time Taken",
        type: "dropdown",
        options: ["Morning", "Afternoon", "Evening", "Bedtime", "As Needed"],
      },
      { name: "Blood Pressure", type: "text" },
      { name: "Heart Rate (bpm)", type: "number" },
      { name: "Temperature (°F/°C)", type: "number" },
      { name: "Blood Sugar", type: "number" },
      { name: "Weight (kg/lb)", type: "number" },
      {
        name: "Symptoms",
        type: "checkbox",
        options: [
          "Pain",
          "Fatigue",
          "Nausea",
          "Headache",
          "Dizziness",
          "Fever",
          "Cough",
          "Rash",
          "Anxiety",
          "Depression",
          "Other",
        ],
      },
      {
        name: "Symptom Severity",
        type: "dropdown",
        options: ["1 - Mild", "2 - Moderate", "3 - Severe", "4 - Very Severe", "5 - Extreme"],
      },
      { name: "Doctor/Provider", type: "text" },
      { name: "Diagnosis", type: "text" },
      { name: "Treatment Plan", type: "textarea" },
      { name: "Test Results", type: "textarea" },
      { name: "Side Effects", type: "textarea" },
      { name: "Diet Notes", type: "textarea" },
      { name: "Notes", type: "textarea" },
      { name: "Documents & Images", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Personal Finance & Budgeting",
    fields: [
      { name: "Date", type: "date" },
      { name: "Description", type: "text" },
      { name: "Amount", type: "number" },
      {
        name: "Type",
        type: "dropdown",
        options: ["Income", "Expense", "Transfer", "Investment", "Savings"],
      },
      {
        name: "Category",
        type: "dropdown",
        options: [
          "Housing",
          "Utilities",
          "Groceries",
          "Dining Out",
          "Transportation",
          "Healthcare",
          "Insurance",
          "Debt Payment",
          "Entertainment",
          "Shopping",
          "Personal Care",
          "Education",
          "Gifts/Donations",
          "Travel",
          "Salary",
          "Investment Income",
          "Other Income",
          "Other Expense",
        ],
      },
      { name: "Account", type: "text" },
      { name: "Payee/Payer", type: "text" },
      {
        name: "Payment Method",
        type: "dropdown",
        options: ["Cash", "Credit Card", "Debit Card", "Bank Transfer", "Check", "Mobile Payment", "Automatic Payment"],
      },
      {
        name: "Status",
        type: "dropdown",
        options: ["Pending", "Completed", "Recurring", "Cancelled"],
      },
      { name: "Due Date", type: "date" },
      {
        name: "Necessity",
        type: "dropdown",
        options: ["Essential", "Important", "Optional", "Luxury"],
      },
      {
        name: "Tags",
        type: "checkbox",
        options: [
          "Tax Deductible",
          "Reimbursable",
          "Shared Expense",
          "Business",
          "Personal",
          "One-time",
          "Subscription",
        ],
      },
      { name: "Budget Category", type: "text" },
      { name: "Budget Allocation", type: "number" },
      { name: "Receipt/Invoice", type: "gallery" },
      { name: "Notes", type: "textarea" },
    ],
    records: [],
  },
  {
    title: "Travel Planner & Bucket List",
    fields: [
      { name: "Destination", type: "text" },
      { name: "Description", type: "textarea" },
      {
        name: "Trip Type",
        type: "dropdown",
        options: [
          "Vacation",
          "Business",
          "Weekend Getaway",
          "Road Trip",
          "International",
          "Domestic",
          "Cruise",
          "Adventure",
          "Relaxation",
          "Cultural",
        ],
      },
      {
        name: "Status",
        type: "dropdown",
        options: ["Bucket List", "Planning", "Booked", "Completed", "Cancelled", "Postponed"],
      },
      { name: "Start Date", type: "date" },
      { name: "End Date", type: "date" },
      { name: "Duration (days)", type: "number" },
      { name: "Budget", type: "number" },
      { name: "Actual Cost", type: "number" },
      { name: "Accommodation", type: "text" },
      { name: "Transportation", type: "text" },
      { name: "Flight/Train/Bus Info", type: "text" },
      { name: "Travel Companions", type: "text" },
      {
        name: "Priority",
        type: "dropdown",
        options: ["Low", "Medium", "High", "Must Do"],
      },
      { name: "Booking References", type: "textarea" },
      { name: "Places to Visit", type: "textarea" },
      { name: "Activities", type: "textarea" },
      { name: "Restaurants & Food", type: "textarea" },
      { name: "Packing List", type: "textarea" },
      { name: "Notes", type: "textarea" },
      { name: "Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Home Inventory & Maintenance",
    fields: [
      { name: "Item Name", type: "text" },
      { name: "Description", type: "textarea" },
      {
        name: "Category",
        type: "dropdown",
        options: [
          "Furniture",
          "Electronics",
          "Appliances",
          "Kitchenware",
          "Decor",
          "Tools",
          "Clothing",
          "Jewelry",
          "Art",
          "Collectibles",
          "Sports Equipment",
          "Outdoor",
          "Documents",
          "Other",
        ],
      },
      { name: "Location/Room", type: "text" },
      { name: "Purchase Date", type: "date" },
      { name: "Purchase Price", type: "number" },
      { name: "Current Value", type: "number" },
      { name: "Serial Number", type: "text" },
      { name: "Model Number", type: "text" },
      { name: "Manufacturer/Brand", type: "text" },
      { name: "Warranty Expiration", type: "date" },
      { name: "Seller/Store", type: "text" },
      { name: "Condition", type: "dropdown", options: ["New", "Excellent", "Good", "Fair", "Poor", "Needs Repair"] },
      { name: "Insurance Coverage", type: "text" },
      { name: "Last Maintenance", type: "date" },
      { name: "Next Maintenance Due", type: "date" },
      { name: "Maintenance History", type: "textarea" },
      {
        name: "Tags",
        type: "checkbox",
        options: ["Insured", "Heirloom", "Valuable", "Borrowed", "Loaned Out", "Seasonal", "Needs Attention"],
      },
      { name: "Notes", type: "textarea" },
      { name: "Photos & Documents", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Movie & TV Show Watchlist",
    fields: [
      { name: "Title", type: "text" },
      {
        name: "Type",
        type: "dropdown",
        options: ["Movie", "TV Series", "Documentary", "Anime", "Short Film", "Special"],
      },
      { name: "Director/Creator", type: "text" },
      { name: "Main Cast", type: "text" },
      {
        name: "Genre",
        type: "checkbox",
        options: [
          "Action",
          "Adventure",
          "Comedy",
          "Drama",
          "Horror",
          "Thriller",
          "Sci-Fi",
          "Fantasy",
          "Romance",
          "Mystery",
          "Crime",
          "Documentary",
          "Animation",
          "Family",
          "Historical",
        ],
      },
      { name: "Release Year", type: "number" },
      { name: "Runtime/Episodes", type: "text" },
      {
        name: "Status",
        type: "dropdown",
        options: ["Want to Watch", "Currently Watching", "Completed", "On Hold", "Dropped"],
      },
      { name: "Season/Episode Tracker", type: "text" },
      {
        name: "Where to Watch",
        type: "dropdown",
        options: [
          "Netflix",
          "Hulu",
          "Amazon Prime",
          "Disney+",
          "HBO Max",
          "Apple TV+",
          "Peacock",
          "Paramount+",
          "YouTube",
          "Theater",
          "DVD/Blu-ray",
          "Other",
        ],
      },
      {
        name: "Priority",
        type: "dropdown",
        options: ["Low", "Medium", "High", "Must Watch"],
      },
      {
        name: "Personal Rating",
        type: "dropdown",
        options: ["1 - Terrible", "2 - Poor", "3 - Average", "4 - Good", "5 - Excellent"],
      },
      { name: "IMDB/Rotten Tomatoes Rating", type: "text" },
      { name: "Recommended By", type: "text" },
      { name: "Date Added", type: "date" },
      { name: "Date Watched", type: "date" },
      { name: "Review/Thoughts", type: "textarea" },
      { name: "Notes", type: "textarea" },
      { name: "Images", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Gift Ideas & Shopping List",
    fields: [
      { name: "Item Name", type: "text" },
      { name: "Description", type: "textarea" },
      {
        name: "Category",
        type: "dropdown",
        options: [
          "Clothing",
          "Electronics",
          "Home Goods",
          "Books",
          "Toys",
          "Jewelry",
          "Experience",
          "Food & Drink",
          "Gift Card",
          "Handmade",
          "Hobby Related",
          "Other",
        ],
      },
      { name: "For Whom", type: "text" },
      { name: "Occasion", type: "text" },
      {
        name: "Occasion Type",
        type: "dropdown",
        options: [
          "Birthday",
          "Anniversary",
          "Wedding",
          "Holiday",
          "Graduation",
          "Baby Shower",
          "Housewarming",
          "Thank You",
          "Just Because",
          "Other",
        ],
      },
      { name: "Event Date", type: "date" },
      { name: "Price/Budget", type: "number" },
      { name: "Where to Buy", type: "text" },
      { name: "URL", type: "text" },
      {
        name: "Priority",
        type: "dropdown",
        options: ["Low", "Medium", "High"],
      },
      {
        name: "Status",
        type: "dropdown",
        options: ["Idea", "Researching", "Decided", "Purchased", "Wrapped", "Given", "Returned"],
      },
      { name: "Purchase Date", type: "date" },
      { name: "Actual Cost", type: "number" },
      {
        name: "Tags",
        type: "checkbox",
        options: [
          "Sale Item",
          "Limited Edition",
          "Personalized",
          "Handmade",
          "Practical",
          "Luxury",
          "Experience",
          "Consumable",
        ],
      },
      { name: "Gift Wrapping Ideas", type: "text" },
      { name: "Recipient's Reaction", type: "textarea" },
      { name: "Notes", type: "textarea" },
      { name: "Images", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Meal Planning & Grocery List",
    fields: [
      { name: "Week Of", type: "date" },
      { name: "Monday Breakfast", type: "text" },
      { name: "Monday Lunch", type: "text" },
      { name: "Monday Dinner", type: "text" },
      { name: "Tuesday Breakfast", type: "text" },
      { name: "Tuesday Lunch", type: "text" },
      { name: "Tuesday Dinner", type: "text" },
      { name: "Wednesday Breakfast", type: "text" },
      { name: "Wednesday Lunch", type: "text" },
      { name: "Wednesday Dinner", type: "text" },
      { name: "Thursday Breakfast", type: "text" },
      { name: "Thursday Lunch", type: "text" },
      { name: "Thursday Dinner", type: "text" },
      { name: "Friday Breakfast", type: "text" },
      { name: "Friday Lunch", type: "text" },
      { name: "Friday Dinner", type: "text" },
      { name: "Saturday Breakfast", type: "text" },
      { name: "Saturday Lunch", type: "text" },
      { name: "Saturday Dinner", type: "text" },
      { name: "Sunday Breakfast", type: "text" },
      { name: "Sunday Lunch", type: "text" },
      { name: "Sunday Dinner", type: "text" },
      { name: "Snacks", type: "text" },
      { name: "Grocery List", type: "textarea" },
      {
        name: "Dietary Focus",
        type: "checkbox",
        options: [
          "Balanced",
          "Low-Carb",
          "High-Protein",
          "Vegetarian",
          "Vegan",
          "Gluten-Free",
          "Dairy-Free",
          "Keto",
          "Paleo",
          "Budget-Friendly",
        ],
      },
      { name: "Prep Notes", type: "textarea" },
      { name: "Shopping Budget", type: "number" },
      { name: "Actual Spent", type: "number" },
      { name: "Meal Photos", type: "gallery" },
    ],
    records: [],
  },
  {
    title: "Hobby & Collection Database",
    fields: [
      { name: "Item Name", type: "text" },
      { name: "Description", type: "textarea" },
      {
        name: "Collection Type",
        type: "dropdown",
        options: [
          "Books",
          "Comics",
          "Vinyl Records",
          "Coins",
          "Stamps",
          "Trading Cards",
          "Action Figures",
          "Model Kits",
          "Art",
          "Antiques",
          "Sports Memorabilia",
          "Wine",
          "Other",
        ],
      },
      { name: "Manufacturer/Publisher", type: "text" },
      { name: "Artist/Author/Creator", type: "text" },
      { name: "Year/Edition", type: "text" },
      { name: "Serial/ISBN Number", type: "text" },
      { name: "Acquisition Date", type: "date" },
      { name: "Purchase Price", type: "number" },
      { name: "Current Value", type: "number" },
      { name: "Purchased From", type: "text" },
      {
        name: "Condition",
        type: "dropdown",
        options: ["Mint", "Near Mint", "Excellent", "Very Good", "Good", "Fair", "Poor", "Damaged"],
      },
      {
        name: "Rarity",
        type: "dropdown",
        options: ["Common", "Uncommon", "Rare", "Very Rare", "Ultra Rare", "One of a Kind"],
      },
      { name: "Storage Location", type: "text" },
      {
        name: "Status",
        type: "dropdown",
        options: ["In Collection", "Wishlist", "For Trade", "For Sale", "Loaned Out", "Missing", "Sold"],
      },
      {
        name: "Tags",
        type: "checkbox",
        options: ["Favorite", "Limited Edition", "Signed", "First Edition", "Vintage", "Sealed", "Complete Set"],
      },
      { name: "Notes", type: "textarea" },
      { name: "History/Provenance", type: "textarea" },
      { name: "Images", type: "gallery" },
    ],
    records: [],
  },
]

